name: Create Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "release.zip"
          exclusions: "*.git* /*node_modules/* .editorconfig"
      - uses: ncipollo/release-action@v1.12.0
      - name: Upload Release
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
